name: 'Build and Push Multi-Arch Image'

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'release-*'
    tags:
      - 'v*'

concurrency:
  group: march-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-quay:
    name: Build and Push Manifest
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - name: Build Operator Container
      uses: konveyor/release-tools/build-push-quay@main
      with:
        architectures: "amd64, arm64, ppc64le, s390x"
        containerfile: "./Dockerfile"
        image_name: "tackle2-operator"
        image_namespace: "konveyor"
        image_registry: "quay.io"
        quay_publish_robot: ${{ secrets.QUAY_PUBLISH_ROBOT }}
        quay_publish_token: ${{ secrets.QUAY_PUBLISH_TOKEN }}
        ref: ${{ github.ref }}

    - name: Build Operator Bundle
      uses: konveyor/release-tools/build-push-quay@main
      with:
        architectures: "amd64"
        containerfile: "./bundle.Dockerfile"
        image_name: "tackle2-operator-bundle"
        image_namespace: "konveyor"
        image_registry: "quay.io"
        quay_publish_robot: ${{ secrets.QUAY_PUBLISH_ROBOT }}
        quay_publish_token: ${{ secrets.QUAY_PUBLISH_TOKEN }}
        ref: ${{ github.ref }}

    - name: Install opm
      run: wget $(curl -s https://api.github.com/repos/operator-framework/operator-registry/releases/latest | grep 'browser_' | cut -d\" -f4 | grep linux) -O opm && chmod +x opm
      if: ${{ github.ref == 'refs/heads/main' }}

    - name: Build index
      run: ./opm index add -c podman --mode semver --tag quay.io/konveyor/tackle2-operator-index:latest --bundles quay.io/konveyor/tackle2-operator-bundle:latest
      if: ${{ github.ref == 'refs/heads/main' }}

    - name: Push index
      run: podman push quay.io/konveyor/tackle2-operator-index:latest --creds=${{ secrets.QUAY_PUBLISH_ROBOT }}:${{ secrets.QUAY_PUBLISH_TOKEN }}
      if: ${{ github.ref == 'refs/heads/main' }}
